name: MUTscope_cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.10
  - numpy
  - pandas
  - scikit-learn=1.4.2
  - matplotlib
  - seaborn
  - tqdm
  - requests
  - ipykernel
  - jupyterlab
  - pyyaml 

  # PyTorch CPU stack
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1

  # Lightning
  - pytorch-lightning

  # Pip-only packages
  - pip
  - pip:
      - transformers==4.47.1
      - torchmetrics==1.6.0
      - fair-esm==2.0.0
      - lightning-utilities==0.11.9
      - huggingface-hub==0.26.5
      - py3dmol==2.4.2
      - imbalanced-learn==0.12.3
      - aiohttp==3.11.11
      - easydict==1.13
      - tensorflow==2.16.1

